name: Rebase Upstream
on:
  schedule:
    - cron: "0 0 * * 0"  # run once a week
  workflow_dispatch:   # run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0  # required for git rebase
      - uses: ./.github/actions/rebase-upstream
        with:
          upstream: xmrig/xmrig
          branch-remote-base: dev
          branch-to-update: master
          branch-feature: dev
        # with:  # all args are optional
        #   upstream: <user>/<repo>
        #   branch:   master